# Generated by Django 2.2.9 on 2020-01-27 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day', models.DateTimeField()),
                ('event_title', models.TextField()),
                ('event_description', models.TextField(blank=True)),
                ('draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('event_small_image', models.ImageField(blank=True, null=True, upload_to='blog_image/%Y/%m/%d/')),
                ('event_large_image', models.ImageField(blank=True, null=True, upload_to='blog_image/%Y/%m/%d/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('event_manager', models.CharField(blank=True, max_length=48, null=True)),
                ('event_managers_role', models.CharField(blank=True, max_length=48, null=True)),
                ('event_organaization', models.CharField(blank=True, max_length=48, null=True)),
                ('event_location', models.CharField(blank=True, max_length=48, null=True)),
                ('event_time', models.CharField(blank=True, max_length=48, null=True)),
                ('contact_num', models.CharField(blank=True, max_length=48, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_address', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
