# Generated by Django 2.2.9 on 2020-01-26 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 12, 50, 30, 162590, tzinfo=utc)),
        ),
    ]
