# Generated by Django 2.2.9 on 2020-01-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_instructor',
        ),
        migrations.AddField(
            model_name='class',
            name='class_instructor',
            field=models.ManyToManyField(to='academia.Teacher'),
        ),
    ]
