# Generated by Django 2.2.9 on 2020-01-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20200123_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
