# Generated by Django 2.2.9 on 2020-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_auto_20200124_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='class_instructor',
            new_name='teacher',
        ),
    ]
